name: search_series
description: "Flutter app to search for tv shows available from tv maze api"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  design_system:
    path: ./modules/design_system
  dio: ^5.4.1
  either_dart: ^1.0.0
  equatable: ^2.0.5
  get_it: ^7.7.0
  flutter:
    sdk: flutter
  provider: ^6.1.2
  rxdart: ^0.28.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
